version: '3.8'

services:
  nats:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nats-server
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring
      - "6222:6222"  # Clustering
    volumes:
      - nats-data:/data
      - nats-config:/etc/nats
    restart: unless-stopped
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge

volumes:
  nats-data:
  nats-config:
