### Example HTTP request for /token endpoint

POST http://localhost:8080/token?skip_cache=true
Content-Type: application/json

{
  "client_id": "app-ring-tone3",
  "client_secret": "P9uPa8dIdhVqepCI7qrcOuKri5KjMVuY"
}

